name: Test-Register

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-app:

    name: Test App

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run application
      run: |
        cd src/
        python pipeline.py